name: Build Image 
on:
    push:
        branches:
            - main
            - 'dev-*'
    pull_request:
        branches:
            - main
            - 'dev-*'
jobs:
    build-an-artifact:
        outputs:
            image-tags:
                description: "the image tage"
                value: ${{ steps.var.outputs.dtag }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6
            - name: Docker Setup Build
              uses: docker/setup-buildx-action@v4 
            - name: Create commit Tag
              id: var 
              run: |
                echo "dtag=${{ github.run_id }}-${GITHUB_SHA::7}" >> ${GITHUB_OUTPUT}
            - name: Build Image By Action
              uses: docker/build-push-action@v7
              with:
                context: .
                file: './Dockerfile'
                push: false
                load: true
                tags: my-app:${{ steps.var.outputs.dtag }}
            # - name: Build Image (no Push)
            #   run: |
            #     TAGS="${{ steps.var.outputs.dtag}}"
            #     docker build -t my-app:$TAGS .

            - name: Save Image Tar
              run : |
                 docker image ls
                 TAGS="${{ steps.var.outputs.dtag}}" 
                 docker save -o my-app-image.tar my-app:$TAGS

            - name: Upload Artifact
              uses: actions/upload-artifact@v7
              with:
                name: docker-image-artifact
                path: my-app-image.tar
    publish-image:
        needs: build-an-artifact
        runs-on: ubuntu-latest
        steps:
            - name : download-image
              uses: actions/download-artifact@v8
              with:
                name: docker-image-artifact
                path: .
            - name: Load Docker Image
              run: docker load -i my-app-image.tar
            - name:Login to Docker Hub
              uses: docker/login-action@v4
              with:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_TOKEN }}
            - name: Add TAG Image
              run: |
                TAGS=${{ needs.build-an-artifact.outputs.image-tags }}
                docker image tag my-app:$TAGS ${{ secrets.DOCKER_USER }}/my-app:$TAGS
            - name: Push Image
              run: |
                TAGS=${{ needs.build-an-artifact.outputs.image-tags }}
                docker image push ${{ secrets.DOCKER_USER }}/my-app:$TAGS



              