name: Build Image 
on:
    push:
        branches:
            - main
            - 'dev-*'
    pull_request:
        branches:
            - main
            - 'dev-*'
jobs:
    build-an-artifact:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6
            - name: Docker Setup Build
              uses: docker/setup-buildx-action@v4 
            - name: Create commit Tag
              id: var 
              run: |
                echo "dtag=${{ github.run_id }}-${GITHUB_SHA::7}" >> ${GITHUB_OUTPUT}
            - name: Build Image By Action
              uses: docker/build-push-action@v7
              with:
                context:
                file: './Dockerfile'
                push: false
                tags: my-app:${{ steps.var.outputs.dtag }}
            # - name: Build Image (no Push)
            #   run: |
            #     TAGS="${{ steps.var.outputs.dtag}}"
            #     docker build -t my-app:$TAGS .

            - name: Save Image Tar
              run : |
                 TAGS="${{ steps.var.outputs.dtag}}" 
                 docker save -o my-app-image.tar my-app:$TAGS

            - name: Upload Artifact
              uses: actions/upload-artifact@v7
              with:
                name: docker-image-artifact
                path: my-app-image.tar


              